# Site settings
title: "Hồ Thiện Ái - Blog"
description: "Kỹ sư phần mềm nhúng ô tô | Chia sẻ kiến thức & kinh nghiệm thực tế"
url: "https://ai-ho.github.io"
baseurl: ""

# Google Analytics
google_analytics: "G-CQRTK1N3QH"

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins (GitHub Pages whitelist)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Gemfile
  - Gemfile.lock

# Include files
include:
  - _pages
