# Site settings
title: "Hồ Thiện Ái - Blog"
description: "Kỹ sư phần mềm nhúng ô tô | Chia sẻ kiến thức & kinh nghiệm thực tế"
url: "https://ai-ho.github.io"
baseurl: ""

# Google Analytics - Change this to your actual ID
google_analytics: "G-CQRTK1N3QH"

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages settings
theme: minima

# Plugins (GitHub Pages whitelist)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
